### PR TITLE
Fix duplicate lv names

### LINKED ISSUE #126: LV name duplicates
**Describe the bug**
If a LV consists of some dm-linear's, `*VolumeGroup.ListVolumes()` returns a slice in which the LV name duplicates.
Due to this, something might go wrong in a production environment where LV's are usually resized.

**Environments**
- Version: any
- OS: Linux

**To Reproduce**
Update the test case in which `*VolumeGroup.ListVolumes()` is called, to make one of the LVs is splitted into more than one dm-linear.

e.g.
1. create lv1 whose size is 1GiB
2. create lv2 whose size is 1GiB
3. resize lv1 to 2GiB

then lv1 is splitted into two dm-linear's.

- https://github.com/nishitaniyuki/topolvm/commit/9ada73b7cbcfed520950bc8b06967f462ead8514
- https://circleci.com/gh/nishitaniyuki/topolvm/52

I updated the test case for `VGService`, please check it :)

**Expected behavior**
Even if a LV consists of some dm-linear's, `*VolumeGroup.ListVolumes()` should return a slice which has no duplicate LV name.

**Additional context**
This problem occurs because inside `*VolumeGroup.ListVolumes` [`lvs` command is called with `thin_count` option](https://github.com/cybozu-go/topolvm/blob/74c520cb16a01a71cc58a76dddbc321d2c708fc3/lvmd/command/lvm.go#L211), [which is classified as a segment option](https://sourceware.org/git/?p=lvm2.git;a=blob;f=lib/report/properties.c;h=325750559399db296f1da0c7002521e6fbbbc62b;hb=HEAD#l531).
`lvs` command seems to output multiple lines per a LV, when it consists of more than one segment(I interpret a segment as a set of continuous blocks) and some segment options is passed.

w/ `thin_count` option:
```
~/src/github.com/cybozu-go/topolvm
❯ sudo lvs -o lv_name,lv_path,lv_size,lv_kernel_major,lv_kernel_minor,origin,origin_size,pool_lv,thin_count,lv_tags --noheadings --separator=' ' --units=b --nosuffix --unbuffered --nameprefixes /dev/vg1/lv1
LVM2_LV_NAME='lv1' LVM2_LV_PATH='/dev/vg1/lv1' LVM2_LV_SIZE='279172874240' LVM2_LV_KERNEL_MAJOR='252' LVM2_LV_KERNEL_MINOR='5' LVM2_ORIGIN='' LVM2_ORIGIN_SIZE='' LVM2_POOL_LV='' LVM2_THIN_COUNT='' LVM2_LV_TAGS=''
LVM2_LV_NAME='lv1' LVM2_LV_PATH='/dev/vg1/lv1' LVM2_LV_SIZE='279172874240' LVM2_LV_KERNEL_MAJOR='252' LVM2_LV_KERNEL_MINOR='5' LVM2_ORIGIN='' LVM2_ORIGIN_SIZE='' LVM2_POOL_LV='' LVM2_THIN_COUNT='' LVM2_LV_TAGS=''
~/src/github.com/cybozu-go/topolvm
❯ 
```

w/o `thin_count` option:
```
~/src/github.com/cybozu-go/topolvm
❯ sudo lvs -o lv_name,lv_path,lv_size,lv_kernel_major,lv_kernel_minor,origin,origin_size,pool_lv,lv_tags --noheadings --separator=' ' --units=b --nosuffix --unbuffered --nameprefixes /dev/vg1/lv1
LVM2_LV_NAME='lv1' LVM2_LV_PATH='/dev/vg1/lv1' LVM2_LV_SIZE='279172874240' LVM2_LV_KERNEL_MAJOR='252' LVM2_LV_KERNEL_MINOR='5' LVM2_ORIGIN='' LVM2_ORIGIN_SIZE='' LVM2_POOL_LV='' LVM2_THIN_COUNT='' LVM2_LV_TAGS=''
~/src/github.com/cybozu-go/topolvm
❯ 
```

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR fixed #126

### CODE REVIEW

File: lvmd/command/lvm.go [hunk 1]
```diff
@@ -214,10 +214,15 @@ func (g *VolumeGroup) ListVolumes() ([]*LogicalVolume, error) {
 		return nil, err
 	}
 	var ret []*LogicalVolume
+	lvNameSet := make(map[string]struct{})
 	for _, info := range infoList {
 		if len(info["thin_count"]) > 0 {
 			continue
 		}
+		if _, ok := lvNameSet[info["lv_name"]]; ok {
```
Comment (ymmt2005) [inline lvmd/command/lvm.go:222]: Please add comments to describe the intention of this code.

**Comment by ysksuzuki** [comment]
> Please check other `lvs` usage, too.

Checked the `lvs` command [here](https://github.com/cybozu-go/topolvm/blob/4abe68ba78932af58397d08e98043c6aad15a864/lvmd/command/lvm.go#L297)

We don't need to change `lvs` command usage in `ListPool()` because thin_pool isn't divided with segments.

We checked it on our local environment.
(Create 2 LVs with type thin_pool(pool1, pool2), resize pool1 and list the LVs with `lvs`, then pool1 isn't duplicated )
